# coding: utf-8

"""
    Glowmarkt User System

    The document enlists and describes the APIs for the User.  # noqa: E501

    OpenAPI spec version: 1.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.o_auth_code_res import OAuthCodeRes  # noqa: E501
from swagger_client.rest import ApiException


class TestOAuthCodeRes(unittest.TestCase):
    """OAuthCodeRes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOAuthCodeRes(self):
        """Test OAuthCodeRes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.o_auth_code_res.OAuthCodeRes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
