# coding: utf-8

"""
    Glowmarkt User System

    The document enlists and describes the APIs for the User.  # noqa: E501

    OpenAPI spec version: 1.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.mpxn_elem import MpxnElem  # noqa: E501
from swagger_client.rest import ApiException


class TestMpxnElem(unittest.TestCase):
    """MpxnElem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMpxnElem(self):
        """Test MpxnElem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.mpxn_elem.MpxnElem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
