# coding: utf-8

"""
Glowmarkt User System

The document enlists and describes the APIs for the User.  # noqa: E501

OpenAPI spec version: 1.0.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import python_glowmarkt
from python_glowmarkt.api.o_auth_api import OAuthApi  # noqa: E501
from python_glowmarkt.rest import ApiException


class TestOAuthApi(unittest.TestCase):
    """OAuthApi unit test stubs"""

    def setUp(self):
        self.api = OAuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_exchange_authorization_code_with_access(self):
        """Test case for exchange_authorization_code_with_access

        Exchange the Authorization Code for an Access Token.  # noqa: E501
        """
        pass

    def test_generate_o_authorization_code(self):
        """Test case for generate_o_authorization_code

        Authenticate a user and generate an OAuth 2.0 Authorization Code Grant.  # noqa: E501
        """
        pass

    def test_validate_o_auth_access_token(self):
        """Test case for validate_o_auth_access_token

        Check and validate an Oauth Access token.  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
