# coding: utf-8

"""
Glowmarkt User System

The document enlists and describes the APIs for the User.  # noqa: E501

OpenAPI spec version: 1.0.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import python_glowmarkt
from python_glowmarkt.api.meter_point_consent__verification_api import (
    MeterPointConsentVerificationApi,
)  # noqa: E501
from python_glowmarkt.rest import ApiException


class TestMeterPointConsentVerificationApi(unittest.TestCase):
    """MeterPointConsentVerificationApi unit test stubs"""

    def setUp(self):
        self.api = MeterPointConsentVerificationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_meter_point_consent_renewal(self):
        """Test case for get_meter_point_consent_renewal

        Get meter point consent renewals  # noqa: E501
        """
        pass

    def test_get_meter_point_consent_revocation(self):
        """Test case for get_meter_point_consent_revocation

        Get meter point consent revocations  # noqa: E501
        """
        pass

    def test_get_user_meter_point_verification_consent_status(self):
        """Test case for get_user_meter_point_verification_consent_status

        API to retrieve user's meter points' consent and verification  # noqa: E501
        """
        pass

    def test_renew_meter_point_consent(self):
        """Test case for renew_meter_point_consent

        Renew meter point consent  # noqa: E501
        """
        pass

    def test_renew_meter_point_consent_bulk(self):
        """Test case for renew_meter_point_consent_bulk

        Renew consent for a number of meterpoints  # noqa: E501
        """
        pass

    def test_renew_meter_point_consent_revoke_bulk(self):
        """Test case for renew_meter_point_consent_revoke_bulk

        Revoke consent for a number of meterpoints  # noqa: E501
        """
        pass

    def test_revoke_meter_point_consent(self):
        """Test case for revoke_meter_point_consent

        Revoke meter point consent  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
