# coding: utf-8

"""
    Glowmarkt User System

    The document enlists and describes the APIs for the User.  # noqa: E501

    OpenAPI spec version: 1.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.user_change_username_admin_body_req import UserChangeUsernameAdminBodyReq  # noqa: E501
from swagger_client.rest import ApiException


class TestUserChangeUsernameAdminBodyReq(unittest.TestCase):
    """UserChangeUsernameAdminBodyReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserChangeUsernameAdminBodyReq(self):
        """Test UserChangeUsernameAdminBodyReq"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_change_username_admin_body_req.UserChangeUsernameAdminBodyReq()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
