# coding: utf-8

"""
Glowmarkt User System

The document enlists and describes the APIs for the User.  # noqa: E501

OpenAPI spec version: 1.0.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import python_glowmarkt
from python_glowmarkt.api.auth_api import AuthApi  # noqa: E501
from python_glowmarkt.rest import ApiException


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self):
        self.api = AuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tokencheck(self):
        """Test case for tokencheck

        Checks whether a user token is valid.  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
