# coding: utf-8

"""
    Glowmarkt User System

    The document enlists and describes the APIs for the User.  # noqa: E501

    OpenAPI spec version: 1.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.remove_mobile_token_to_account_req import RemoveMobileTokenToAccountReq  # noqa: E501
from swagger_client.rest import ApiException


class TestRemoveMobileTokenToAccountReq(unittest.TestCase):
    """RemoveMobileTokenToAccountReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRemoveMobileTokenToAccountReq(self):
        """Test RemoveMobileTokenToAccountReq"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.remove_mobile_token_to_account_req.RemoveMobileTokenToAccountReq()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
