# coding: utf-8

"""
    Glowmarkt User System

    The document enlists and describes the APIs for the User.  # noqa: E501

    OpenAPI spec version: 1.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.user_meter_point_consent_and_verification import UserMeterPointConsentAndVerification  # noqa: E501
from swagger_client.rest import ApiException


class TestUserMeterPointConsentAndVerification(unittest.TestCase):
    """UserMeterPointConsentAndVerification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserMeterPointConsentAndVerification(self):
        """Test UserMeterPointConsentAndVerification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_meter_point_consent_and_verification.UserMeterPointConsentAndVerification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
