# coding: utf-8

"""
Glowmarkt User System

The document enlists and describes the APIs for the User.  # noqa: E501

OpenAPI spec version: 1.0.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import python_glowmarkt
from python_glowmarkt.models.meter_point_verification_renewal_elem import (
    MeterPointVerificationRenewalElem,
)  # noqa: E501
from python_glowmarkt.rest import ApiException


class TestMeterPointVerificationRenewalElem(unittest.TestCase):
    """MeterPointVerificationRenewalElem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMeterPointVerificationRenewalElem(self):
        """Test MeterPointVerificationRenewalElem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = python_glowmarkt.models.meter_point_verification_renewal_elem.MeterPointVerificationRenewalElem()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
