# coding: utf-8

"""
    Glowmarkt User System

    The document enlists and describes the APIs for the User.  # noqa: E501

    OpenAPI spec version: 1.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user_api import UserApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_user(self):
        """Test case for add_user

        Create a user  # noqa: E501
        """
        pass

    def test_create_user(self):
        """Test case for create_user

        Create a user  # noqa: E501
        """
        pass

    def test_delete_userby_id(self):
        """Test case for delete_userby_id

        Delete specific user. This will delete all the accounts of a user. Please refer to delete account API. This API requires specific permissions.  # noqa: E501
        """
        pass

    def test_generate_user_password_reset_token(self):
        """Test case for generate_user_password_reset_token

        Generate a token that can be used by user to reset their password.  # noqa: E501
        """
        pass

    def test_generate_user_verification_token(self):
        """Test case for generate_user_verification_token

        Generate a user verification token  # noqa: E501
        """
        pass

    def test_get_userby_id(self):
        """Test case for get_userby_id

        Find specific user that has an account in an application.  # noqa: E501
        """
        pass

    def test_get_userby_username(self):
        """Test case for get_userby_username

        Find specific user that has an account in an application from the username.  # noqa: E501
        """
        pass

    def test_reset_password_user(self):
        """Test case for reset_password_user

        A user resets their password  # noqa: E501
        """
        pass

    def test_update_username_user_id(self):
        """Test case for update_username_user_id

        Change a user's username  # noqa: E501
        """
        pass

    def test_verify_user(self):
        """Test case for verify_user

        Verify a user verification token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
