# coding: utf-8

"""
Glowmarkt User System

The document enlists and describes the APIs for the User.  # noqa: E501

OpenAPI spec version: 1.0.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import python_glowmarkt
from python_glowmarkt.models.meter_point_consent_management_bulk_revocation_res import (
    MeterPointConsentManagementBulkRevocationRes,
)  # noqa: E501
from python_glowmarkt.rest import ApiException


class TestMeterPointConsentManagementBulkRevocationRes(unittest.TestCase):
    """MeterPointConsentManagementBulkRevocationRes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMeterPointConsentManagementBulkRevocationRes(self):
        """Test MeterPointConsentManagementBulkRevocationRes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = python_glowmarkt.models.meter_point_consent_management_bulk_revocation_res.MeterPointConsentManagementBulkRevocationRes()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
