# coding: utf-8

"""
Glowmarkt User System

The document enlists and describes the APIs for the User.  # noqa: E501

OpenAPI spec version: 1.0.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import python_glowmarkt
from python_glowmarkt.models.o_auth_valid_access_token import OAuthValidAccessToken  # noqa: E501
from python_glowmarkt.rest import ApiException


class TestOAuthValidAccessToken(unittest.TestCase):
    """OAuthValidAccessToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOAuthValidAccessToken(self):
        """Test OAuthValidAccessToken"""
        # FIXME: construct object with mandatory attributes with example values
        # model = python_glowmarkt.models.o_auth_valid_access_token.OAuthValidAccessToken()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
