# coding: utf-8

"""
    Glowmarkt User System

    The document enlists and describes the APIs for the User.  # noqa: E501

    OpenAPI spec version: 1.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2009(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'exp': 'int',
        'token': 'str',
        'valid': 'bool'
    }

    attribute_map = {
        'exp': 'exp',
        'token': 'token',
        'valid': 'valid'
    }

    def __init__(self, exp=None, token=None, valid=None):  # noqa: E501
        """InlineResponse2009 - a model defined in Swagger"""  # noqa: E501
        self._exp = None
        self._token = None
        self._valid = None
        self.discriminator = None
        if exp is not None:
            self.exp = exp
        if token is not None:
            self.token = token
        if valid is not None:
            self.valid = valid

    @property
    def exp(self):
        """Gets the exp of this InlineResponse2009.  # noqa: E501

        Timestamp of token expiry date  # noqa: E501

        :return: The exp of this InlineResponse2009.  # noqa: E501
        :rtype: int
        """
        return self._exp

    @exp.setter
    def exp(self, exp):
        """Sets the exp of this InlineResponse2009.

        Timestamp of token expiry date  # noqa: E501

        :param exp: The exp of this InlineResponse2009.  # noqa: E501
        :type: int
        """

        self._exp = exp

    @property
    def token(self):
        """Gets the token of this InlineResponse2009.  # noqa: E501

        A new valid token for an account  # noqa: E501

        :return: The token of this InlineResponse2009.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this InlineResponse2009.

        A new valid token for an account  # noqa: E501

        :param token: The token of this InlineResponse2009.  # noqa: E501
        :type: str
        """

        self._token = token

    @property
    def valid(self):
        """Gets the valid of this InlineResponse2009.  # noqa: E501


        :return: The valid of this InlineResponse2009.  # noqa: E501
        :rtype: bool
        """
        return self._valid

    @valid.setter
    def valid(self, valid):
        """Sets the valid of this InlineResponse2009.


        :param valid: The valid of this InlineResponse2009.  # noqa: E501
        :type: bool
        """

        self._valid = valid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2009, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2009):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
