# coding: utf-8

"""
    Glowmarkt User System

    The document enlists and describes the APIs for the User.  # noqa: E501

    OpenAPI spec version: 1.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MeterPointVerificationRevocationElem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_valid_until': 'str',
        'meter_point_verification_revocation_id': 'str',
        'mpxn': 'str',
        'valid': 'bool'
    }

    attribute_map = {
        'is_valid_until': 'isValidUntil',
        'meter_point_verification_revocation_id': 'meterPointVerificationRevocationId',
        'mpxn': 'mpxn',
        'valid': 'valid'
    }

    def __init__(self, is_valid_until=None, meter_point_verification_revocation_id=None, mpxn=None, valid=None):  # noqa: E501
        """MeterPointVerificationRevocationElem - a model defined in Swagger"""  # noqa: E501
        self._is_valid_until = None
        self._meter_point_verification_revocation_id = None
        self._mpxn = None
        self._valid = None
        self.discriminator = None
        if is_valid_until is not None:
            self.is_valid_until = is_valid_until
        if meter_point_verification_revocation_id is not None:
            self.meter_point_verification_revocation_id = meter_point_verification_revocation_id
        if mpxn is not None:
            self.mpxn = mpxn
        if valid is not None:
            self.valid = valid

    @property
    def is_valid_until(self):
        """Gets the is_valid_until of this MeterPointVerificationRevocationElem.  # noqa: E501


        :return: The is_valid_until of this MeterPointVerificationRevocationElem.  # noqa: E501
        :rtype: str
        """
        return self._is_valid_until

    @is_valid_until.setter
    def is_valid_until(self, is_valid_until):
        """Sets the is_valid_until of this MeterPointVerificationRevocationElem.


        :param is_valid_until: The is_valid_until of this MeterPointVerificationRevocationElem.  # noqa: E501
        :type: str
        """

        self._is_valid_until = is_valid_until

    @property
    def meter_point_verification_revocation_id(self):
        """Gets the meter_point_verification_revocation_id of this MeterPointVerificationRevocationElem.  # noqa: E501


        :return: The meter_point_verification_revocation_id of this MeterPointVerificationRevocationElem.  # noqa: E501
        :rtype: str
        """
        return self._meter_point_verification_revocation_id

    @meter_point_verification_revocation_id.setter
    def meter_point_verification_revocation_id(self, meter_point_verification_revocation_id):
        """Sets the meter_point_verification_revocation_id of this MeterPointVerificationRevocationElem.


        :param meter_point_verification_revocation_id: The meter_point_verification_revocation_id of this MeterPointVerificationRevocationElem.  # noqa: E501
        :type: str
        """

        self._meter_point_verification_revocation_id = meter_point_verification_revocation_id

    @property
    def mpxn(self):
        """Gets the mpxn of this MeterPointVerificationRevocationElem.  # noqa: E501


        :return: The mpxn of this MeterPointVerificationRevocationElem.  # noqa: E501
        :rtype: str
        """
        return self._mpxn

    @mpxn.setter
    def mpxn(self, mpxn):
        """Sets the mpxn of this MeterPointVerificationRevocationElem.


        :param mpxn: The mpxn of this MeterPointVerificationRevocationElem.  # noqa: E501
        :type: str
        """

        self._mpxn = mpxn

    @property
    def valid(self):
        """Gets the valid of this MeterPointVerificationRevocationElem.  # noqa: E501


        :return: The valid of this MeterPointVerificationRevocationElem.  # noqa: E501
        :rtype: bool
        """
        return self._valid

    @valid.setter
    def valid(self, valid):
        """Sets the valid of this MeterPointVerificationRevocationElem.


        :param valid: The valid of this MeterPointVerificationRevocationElem.  # noqa: E501
        :type: bool
        """

        self._valid = valid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MeterPointVerificationRevocationElem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MeterPointVerificationRevocationElem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
