# coding: utf-8

"""
    Glowmarkt User System

    The document enlists and describes the APIs for the User.  # noqa: E501

    OpenAPI spec version: 1.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MeterPointConsentManagementBulkReq(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'meter_points': 'list[MpxnElem]'
    }

    attribute_map = {
        'meter_points': 'meterPoints'
    }

    def __init__(self, meter_points=None):  # noqa: E501
        """MeterPointConsentManagementBulkReq - a model defined in Swagger"""  # noqa: E501
        self._meter_points = None
        self.discriminator = None
        if meter_points is not None:
            self.meter_points = meter_points

    @property
    def meter_points(self):
        """Gets the meter_points of this MeterPointConsentManagementBulkReq.  # noqa: E501


        :return: The meter_points of this MeterPointConsentManagementBulkReq.  # noqa: E501
        :rtype: list[MpxnElem]
        """
        return self._meter_points

    @meter_points.setter
    def meter_points(self, meter_points):
        """Sets the meter_points of this MeterPointConsentManagementBulkReq.


        :param meter_points: The meter_points of this MeterPointConsentManagementBulkReq.  # noqa: E501
        :type: list[MpxnElem]
        """

        self._meter_points = meter_points

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MeterPointConsentManagementBulkReq, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MeterPointConsentManagementBulkReq):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
