# coding: utf-8

"""
    Glowmarkt User System

    The document enlists and describes the APIs for the User.  # noqa: E501

    OpenAPI spec version: 1.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.add_user_res import AddUserRes  # noqa: F401,E501

class OAuthValidAccessToken(AddUserRes):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'authentication_framework': 'str',
        'status': 'str'
    }
    if hasattr(AddUserRes, "swagger_types"):
        swagger_types.update(AddUserRes.swagger_types)

    attribute_map = {
        'authentication_framework': 'authenticationFramework',
        'status': 'status'
    }
    if hasattr(AddUserRes, "attribute_map"):
        attribute_map.update(AddUserRes.attribute_map)

    def __init__(self, authentication_framework=None, status=None, *args, **kwargs):  # noqa: E501
        """OAuthValidAccessToken - a model defined in Swagger"""  # noqa: E501
        self._authentication_framework = None
        self._status = None
        self.discriminator = None
        if authentication_framework is not None:
            self.authentication_framework = authentication_framework
        if status is not None:
            self.status = status
        AddUserRes.__init__(self, *args, **kwargs)

    @property
    def authentication_framework(self):
        """Gets the authentication_framework of this OAuthValidAccessToken.  # noqa: E501


        :return: The authentication_framework of this OAuthValidAccessToken.  # noqa: E501
        :rtype: str
        """
        return self._authentication_framework

    @authentication_framework.setter
    def authentication_framework(self, authentication_framework):
        """Sets the authentication_framework of this OAuthValidAccessToken.


        :param authentication_framework: The authentication_framework of this OAuthValidAccessToken.  # noqa: E501
        :type: str
        """

        self._authentication_framework = authentication_framework

    @property
    def status(self):
        """Gets the status of this OAuthValidAccessToken.  # noqa: E501


        :return: The status of this OAuthValidAccessToken.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this OAuthValidAccessToken.


        :param status: The status of this OAuthValidAccessToken.  # noqa: E501
        :type: str
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OAuthValidAccessToken, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OAuthValidAccessToken):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
