# coding: utf-8

"""
    Glowmarkt User System

    The document enlists and describes the APIs for the User.  # noqa: E501

    OpenAPI spec version: 1.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AccountStatusDirectoryData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'token_expiry_date': 'datetime',
        'token_issue_date': 'datetime'
    }

    attribute_map = {
        'token_expiry_date': 'tokenExpiryDate',
        'token_issue_date': 'tokenIssueDate'
    }

    def __init__(self, token_expiry_date=None, token_issue_date=None):  # noqa: E501
        """AccountStatusDirectoryData - a model defined in Swagger"""  # noqa: E501
        self._token_expiry_date = None
        self._token_issue_date = None
        self.discriminator = None
        if token_expiry_date is not None:
            self.token_expiry_date = token_expiry_date
        if token_issue_date is not None:
            self.token_issue_date = token_issue_date

    @property
    def token_expiry_date(self):
        """Gets the token_expiry_date of this AccountStatusDirectoryData.  # noqa: E501


        :return: The token_expiry_date of this AccountStatusDirectoryData.  # noqa: E501
        :rtype: datetime
        """
        return self._token_expiry_date

    @token_expiry_date.setter
    def token_expiry_date(self, token_expiry_date):
        """Sets the token_expiry_date of this AccountStatusDirectoryData.


        :param token_expiry_date: The token_expiry_date of this AccountStatusDirectoryData.  # noqa: E501
        :type: datetime
        """

        self._token_expiry_date = token_expiry_date

    @property
    def token_issue_date(self):
        """Gets the token_issue_date of this AccountStatusDirectoryData.  # noqa: E501


        :return: The token_issue_date of this AccountStatusDirectoryData.  # noqa: E501
        :rtype: datetime
        """
        return self._token_issue_date

    @token_issue_date.setter
    def token_issue_date(self, token_issue_date):
        """Sets the token_issue_date of this AccountStatusDirectoryData.


        :param token_issue_date: The token_issue_date of this AccountStatusDirectoryData.  # noqa: E501
        :type: datetime
        """

        self._token_issue_date = token_issue_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AccountStatusDirectoryData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccountStatusDirectoryData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
