# coding: utf-8

"""
    Glowmarkt User System

    The document enlists and describes the APIs for the User.  # noqa: E501

    OpenAPI spec version: 1.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AddUserResApplications(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'account_id': 'str',
        'active': 'bool',
        'application_id': 'str'
    }

    attribute_map = {
        'account_id': 'accountId',
        'active': 'active',
        'application_id': 'applicationId'
    }

    def __init__(self, account_id=None, active=None, application_id=None):  # noqa: E501
        """AddUserResApplications - a model defined in Swagger"""  # noqa: E501
        self._account_id = None
        self._active = None
        self._application_id = None
        self.discriminator = None
        if account_id is not None:
            self.account_id = account_id
        if active is not None:
            self.active = active
        if application_id is not None:
            self.application_id = application_id

    @property
    def account_id(self):
        """Gets the account_id of this AddUserResApplications.  # noqa: E501


        :return: The account_id of this AddUserResApplications.  # noqa: E501
        :rtype: str
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this AddUserResApplications.


        :param account_id: The account_id of this AddUserResApplications.  # noqa: E501
        :type: str
        """

        self._account_id = account_id

    @property
    def active(self):
        """Gets the active of this AddUserResApplications.  # noqa: E501


        :return: The active of this AddUserResApplications.  # noqa: E501
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this AddUserResApplications.


        :param active: The active of this AddUserResApplications.  # noqa: E501
        :type: bool
        """

        self._active = active

    @property
    def application_id(self):
        """Gets the application_id of this AddUserResApplications.  # noqa: E501


        :return: The application_id of this AddUserResApplications.  # noqa: E501
        :rtype: str
        """
        return self._application_id

    @application_id.setter
    def application_id(self, application_id):
        """Sets the application_id of this AddUserResApplications.


        :param application_id: The application_id of this AddUserResApplications.  # noqa: E501
        :type: str
        """

        self._application_id = application_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AddUserResApplications, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AddUserResApplications):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
