# coding: utf-8

"""
    Glowmarkt User System

    The document enlists and describes the APIs for the User.  # noqa: E501

    OpenAPI spec version: 1.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2004(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'dev_user_id': 'str',
        'profile_name': 'str',
        'status': 'str'
    }

    attribute_map = {
        'dev_user_id': 'devUserId',
        'profile_name': 'profileName',
        'status': 'status'
    }

    def __init__(self, dev_user_id=None, profile_name=None, status=None):  # noqa: E501
        """InlineResponse2004 - a model defined in Swagger"""  # noqa: E501
        self._dev_user_id = None
        self._profile_name = None
        self._status = None
        self.discriminator = None
        if dev_user_id is not None:
            self.dev_user_id = dev_user_id
        if profile_name is not None:
            self.profile_name = profile_name
        if status is not None:
            self.status = status

    @property
    def dev_user_id(self):
        """Gets the dev_user_id of this InlineResponse2004.  # noqa: E501


        :return: The dev_user_id of this InlineResponse2004.  # noqa: E501
        :rtype: str
        """
        return self._dev_user_id

    @dev_user_id.setter
    def dev_user_id(self, dev_user_id):
        """Sets the dev_user_id of this InlineResponse2004.


        :param dev_user_id: The dev_user_id of this InlineResponse2004.  # noqa: E501
        :type: str
        """

        self._dev_user_id = dev_user_id

    @property
    def profile_name(self):
        """Gets the profile_name of this InlineResponse2004.  # noqa: E501


        :return: The profile_name of this InlineResponse2004.  # noqa: E501
        :rtype: str
        """
        return self._profile_name

    @profile_name.setter
    def profile_name(self, profile_name):
        """Sets the profile_name of this InlineResponse2004.


        :param profile_name: The profile_name of this InlineResponse2004.  # noqa: E501
        :type: str
        """

        self._profile_name = profile_name

    @property
    def status(self):
        """Gets the status of this InlineResponse2004.  # noqa: E501


        :return: The status of this InlineResponse2004.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse2004.


        :param status: The status of this InlineResponse2004.  # noqa: E501
        :type: str
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2004, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2004):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
