# coding: utf-8

"""
    Glowmarkt User System

    The document enlists and describes the APIs for the User.  # noqa: E501

    OpenAPI spec version: 1.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2007(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'account_id': 'str',
        'application_id': 'str',
        'exp': 'int',
        'valid': 'bool'
    }

    attribute_map = {
        'account_id': 'accountId',
        'application_id': 'applicationId',
        'exp': 'exp',
        'valid': 'valid'
    }

    def __init__(self, account_id=None, application_id=None, exp=None, valid=None):  # noqa: E501
        """InlineResponse2007 - a model defined in Swagger"""  # noqa: E501
        self._account_id = None
        self._application_id = None
        self._exp = None
        self._valid = None
        self.discriminator = None
        if account_id is not None:
            self.account_id = account_id
        if application_id is not None:
            self.application_id = application_id
        if exp is not None:
            self.exp = exp
        if valid is not None:
            self.valid = valid

    @property
    def account_id(self):
        """Gets the account_id of this InlineResponse2007.  # noqa: E501


        :return: The account_id of this InlineResponse2007.  # noqa: E501
        :rtype: str
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this InlineResponse2007.


        :param account_id: The account_id of this InlineResponse2007.  # noqa: E501
        :type: str
        """

        self._account_id = account_id

    @property
    def application_id(self):
        """Gets the application_id of this InlineResponse2007.  # noqa: E501


        :return: The application_id of this InlineResponse2007.  # noqa: E501
        :rtype: str
        """
        return self._application_id

    @application_id.setter
    def application_id(self, application_id):
        """Sets the application_id of this InlineResponse2007.


        :param application_id: The application_id of this InlineResponse2007.  # noqa: E501
        :type: str
        """

        self._application_id = application_id

    @property
    def exp(self):
        """Gets the exp of this InlineResponse2007.  # noqa: E501

        Timestamp of token expiry date  # noqa: E501

        :return: The exp of this InlineResponse2007.  # noqa: E501
        :rtype: int
        """
        return self._exp

    @exp.setter
    def exp(self, exp):
        """Sets the exp of this InlineResponse2007.

        Timestamp of token expiry date  # noqa: E501

        :param exp: The exp of this InlineResponse2007.  # noqa: E501
        :type: int
        """

        self._exp = exp

    @property
    def valid(self):
        """Gets the valid of this InlineResponse2007.  # noqa: E501


        :return: The valid of this InlineResponse2007.  # noqa: E501
        :rtype: bool
        """
        return self._valid

    @valid.setter
    def valid(self, valid):
        """Sets the valid of this InlineResponse2007.


        :param valid: The valid of this InlineResponse2007.  # noqa: E501
        :type: bool
        """

        self._valid = valid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2007, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2007):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
