# coding: utf-8

"""
    Glowmarkt User System

    The document enlists and describes the APIs for the User.  # noqa: E501

    OpenAPI spec version: 1.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MeterPointConsentAndVerification(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_valid_until': 'datetime',
        'is_verified': 'bool',
        'mpxn': 'str',
        'mpxn_key': 'str'
    }

    attribute_map = {
        'is_valid_until': 'isValidUntil',
        'is_verified': 'isVerified',
        'mpxn': 'mpxn',
        'mpxn_key': 'mpxnKey'
    }

    def __init__(self, is_valid_until=None, is_verified=None, mpxn=None, mpxn_key=None):  # noqa: E501
        """MeterPointConsentAndVerification - a model defined in Swagger"""  # noqa: E501
        self._is_valid_until = None
        self._is_verified = None
        self._mpxn = None
        self._mpxn_key = None
        self.discriminator = None
        if is_valid_until is not None:
            self.is_valid_until = is_valid_until
        if is_verified is not None:
            self.is_verified = is_verified
        if mpxn is not None:
            self.mpxn = mpxn
        if mpxn_key is not None:
            self.mpxn_key = mpxn_key

    @property
    def is_valid_until(self):
        """Gets the is_valid_until of this MeterPointConsentAndVerification.  # noqa: E501


        :return: The is_valid_until of this MeterPointConsentAndVerification.  # noqa: E501
        :rtype: datetime
        """
        return self._is_valid_until

    @is_valid_until.setter
    def is_valid_until(self, is_valid_until):
        """Sets the is_valid_until of this MeterPointConsentAndVerification.


        :param is_valid_until: The is_valid_until of this MeterPointConsentAndVerification.  # noqa: E501
        :type: datetime
        """

        self._is_valid_until = is_valid_until

    @property
    def is_verified(self):
        """Gets the is_verified of this MeterPointConsentAndVerification.  # noqa: E501


        :return: The is_verified of this MeterPointConsentAndVerification.  # noqa: E501
        :rtype: bool
        """
        return self._is_verified

    @is_verified.setter
    def is_verified(self, is_verified):
        """Sets the is_verified of this MeterPointConsentAndVerification.


        :param is_verified: The is_verified of this MeterPointConsentAndVerification.  # noqa: E501
        :type: bool
        """

        self._is_verified = is_verified

    @property
    def mpxn(self):
        """Gets the mpxn of this MeterPointConsentAndVerification.  # noqa: E501


        :return: The mpxn of this MeterPointConsentAndVerification.  # noqa: E501
        :rtype: str
        """
        return self._mpxn

    @mpxn.setter
    def mpxn(self, mpxn):
        """Sets the mpxn of this MeterPointConsentAndVerification.


        :param mpxn: The mpxn of this MeterPointConsentAndVerification.  # noqa: E501
        :type: str
        """

        self._mpxn = mpxn

    @property
    def mpxn_key(self):
        """Gets the mpxn_key of this MeterPointConsentAndVerification.  # noqa: E501


        :return: The mpxn_key of this MeterPointConsentAndVerification.  # noqa: E501
        :rtype: str
        """
        return self._mpxn_key

    @mpxn_key.setter
    def mpxn_key(self, mpxn_key):
        """Sets the mpxn_key of this MeterPointConsentAndVerification.


        :param mpxn_key: The mpxn_key of this MeterPointConsentAndVerification.  # noqa: E501
        :type: str
        """
        allowed_values = ["mpan", "mprn"]  # noqa: E501
        if mpxn_key not in allowed_values:
            raise ValueError(
                "Invalid value for `mpxn_key` ({0}), must be one of {1}"  # noqa: E501
                .format(mpxn_key, allowed_values)
            )

        self._mpxn_key = mpxn_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MeterPointConsentAndVerification, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MeterPointConsentAndVerification):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
