# coding: utf-8

"""
    Glowmarkt User System

    The document enlists and describes the APIs for the User.  # noqa: E501

    OpenAPI spec version: 1.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MeterPointConsentAndVerificationRevocationRes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'meter_point_renewals': 'list[MeterPointConsentAndVerificationRevocation]',
        'valid': 'bool'
    }

    attribute_map = {
        'meter_point_renewals': 'meterPointRenewals',
        'valid': 'valid'
    }

    def __init__(self, meter_point_renewals=None, valid=None):  # noqa: E501
        """MeterPointConsentAndVerificationRevocationRes - a model defined in Swagger"""  # noqa: E501
        self._meter_point_renewals = None
        self._valid = None
        self.discriminator = None
        if meter_point_renewals is not None:
            self.meter_point_renewals = meter_point_renewals
        if valid is not None:
            self.valid = valid

    @property
    def meter_point_renewals(self):
        """Gets the meter_point_renewals of this MeterPointConsentAndVerificationRevocationRes.  # noqa: E501


        :return: The meter_point_renewals of this MeterPointConsentAndVerificationRevocationRes.  # noqa: E501
        :rtype: list[MeterPointConsentAndVerificationRevocation]
        """
        return self._meter_point_renewals

    @meter_point_renewals.setter
    def meter_point_renewals(self, meter_point_renewals):
        """Sets the meter_point_renewals of this MeterPointConsentAndVerificationRevocationRes.


        :param meter_point_renewals: The meter_point_renewals of this MeterPointConsentAndVerificationRevocationRes.  # noqa: E501
        :type: list[MeterPointConsentAndVerificationRevocation]
        """

        self._meter_point_renewals = meter_point_renewals

    @property
    def valid(self):
        """Gets the valid of this MeterPointConsentAndVerificationRevocationRes.  # noqa: E501


        :return: The valid of this MeterPointConsentAndVerificationRevocationRes.  # noqa: E501
        :rtype: bool
        """
        return self._valid

    @valid.setter
    def valid(self, valid):
        """Sets the valid of this MeterPointConsentAndVerificationRevocationRes.


        :param valid: The valid of this MeterPointConsentAndVerificationRevocationRes.  # noqa: E501
        :type: bool
        """

        self._valid = valid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MeterPointConsentAndVerificationRevocationRes, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MeterPointConsentAndVerificationRevocationRes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
