# coding: utf-8

"""
    Glowmarkt User System

    The document enlists and describes the APIs for the User.  # noqa: E501

    OpenAPI spec version: 1.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PasswordResetUserReq(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'application_id': 'str',
        'new_password': 'str',
        'token': 'str',
        'username': 'str'
    }

    attribute_map = {
        'application_id': 'applicationId',
        'new_password': 'newPassword',
        'token': 'token',
        'username': 'username'
    }

    def __init__(self, application_id=None, new_password=None, token=None, username=None):  # noqa: E501
        """PasswordResetUserReq - a model defined in Swagger"""  # noqa: E501
        self._application_id = None
        self._new_password = None
        self._token = None
        self._username = None
        self.discriminator = None
        self.application_id = application_id
        self.new_password = new_password
        self.token = token
        self.username = username

    @property
    def application_id(self):
        """Gets the application_id of this PasswordResetUserReq.  # noqa: E501


        :return: The application_id of this PasswordResetUserReq.  # noqa: E501
        :rtype: str
        """
        return self._application_id

    @application_id.setter
    def application_id(self, application_id):
        """Sets the application_id of this PasswordResetUserReq.


        :param application_id: The application_id of this PasswordResetUserReq.  # noqa: E501
        :type: str
        """
        if application_id is None:
            raise ValueError("Invalid value for `application_id`, must not be `None`")  # noqa: E501

        self._application_id = application_id

    @property
    def new_password(self):
        """Gets the new_password of this PasswordResetUserReq.  # noqa: E501


        :return: The new_password of this PasswordResetUserReq.  # noqa: E501
        :rtype: str
        """
        return self._new_password

    @new_password.setter
    def new_password(self, new_password):
        """Sets the new_password of this PasswordResetUserReq.


        :param new_password: The new_password of this PasswordResetUserReq.  # noqa: E501
        :type: str
        """
        if new_password is None:
            raise ValueError("Invalid value for `new_password`, must not be `None`")  # noqa: E501

        self._new_password = new_password

    @property
    def token(self):
        """Gets the token of this PasswordResetUserReq.  # noqa: E501


        :return: The token of this PasswordResetUserReq.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this PasswordResetUserReq.


        :param token: The token of this PasswordResetUserReq.  # noqa: E501
        :type: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def username(self):
        """Gets the username of this PasswordResetUserReq.  # noqa: E501


        :return: The username of this PasswordResetUserReq.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this PasswordResetUserReq.


        :param username: The username of this PasswordResetUserReq.  # noqa: E501
        :type: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PasswordResetUserReq, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PasswordResetUserReq):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
